インクリメンタルサーチ実装
hiroaki122/chat-space pull request #7
Opened 2019-03-18 12:36 UTC by hiroaki122

2019-03-18 18:24 UTC, hiroki5123 commented
実際に動いてるところなよgifをこちらに添付してください

2019-03-18 18:27 UTC, ghost requested changes

2019-03-18 18:27 UTC, hiroki5123 commented on app/views/users/index.json.jbuilder
> +end
最後に空行入れましょう

2019-03-18 18:27 UTC, hiroki5123 commented on app/views/groups/_form.html.haml
> +        %input{:name => "chat_group[user_ids][]", :type => "hidden", :value => "22"}/
ハッシュロケットの部分を書き換えましょう

2019-03-18 18:27 UTC, hiroki5123 commented on app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
こちらもハッシュロケット書き換えましょう

2019-03-18 18:27 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +    format.json
doの中なので、インデント一個奥にしましょう

2019-03-18 18:27 UTC, hiroki5123 commented on app/assets/javascripts/user.js
> +});
最後に空行入れましょう

2019-03-19 09:48 UTC, merged

2019-03-26 06:59 UTC, TOMARUMARU commented
指摘されている箇所が全て修正されていないようなのでご確認ください